log_dir: /pub/sheikhh1/bubbleformer_logs
seed: 42

distributed: True
nodes:
devices:

max_epochs:
batch_size: 4

checkpoint_path:

use_wandb: True
wandb_tags:
  - baseline
  - relative_l2_loss
  - AViT-TemporalAttnOnly
  - PB-Saturated
defaults:
  - _self_
  - data_cfg: poolboiling_saturated
  - model_cfg: avit_temporal_small
  - optim_cfg: adamw
  - scheduler_cfg: cosine_warmup
