log_dir: /pub/sheikhh1/bubbleformer_logs
seed: 42

distributed: True
devices: 4

max_epochs: 100
batch_size: 4

checkpoint_path:

use_wandb: True
wandb_tags:
  - baseline
  - relative_l2_loss
  - AViT-S_29M
  - PB-Saturated

defaults:
  - _self_
  - data_cfg: poolboiling_saturated
  - model_cfg: avit_small
  - optim_cfg: adamw
  - scheduler_cfg: cosine_warmup
