log_dir: ./bubbleformer_logs
seed: 42

distributed: True
nodes: 1
devices: 1

# max_epochs: 16
max_epochs: 400
batch_size: 4

# checkpoint_path: ./bubbleformer_logs/Same_size_shared_experts_E_6_S_1_A_2_avit_moe_poolboiling_combined_36342187/lightning_logs/version_0/checkpoints/epoch=341-step=171000.ckpt
checkpoint_path: 
use_wandb: True
wandb_tags:
  - baseline
  - relative_l2_loss
  - AViT-S_29M
  - PB-Combined

defaults:
  - _self_
  - data_cfg: poolboiling_saturated
  - model_cfg: avit_small_moe
  - optim_cfg: adamw
  - scheduler_cfg: cosine_warmup
