log_dir: ./bubbleformer_logs
seed: 42

distributed: True
nodes: 1
devices: 1

max_epochs: 400
batch_size: 4

checkpoint_path:

use_wandb: True
wandb_tags:
  - baseline
  - relative_l2_loss
  - AViT-S_29M
  - PB-Combined

defaults:
  - _self_
  - data_cfg: poolboiling_combined
  - model_cfg: avit_small_moe
  - optim_cfg: adamw
  - scheduler_cfg: cosine_warmup
