log_dir: /pub/sheikhh1/bubbleformer_logs
seed: 42

distributed: True
nodes:
devices:

max_epochs:
batch_size: 2

checkpoint_path:

use_wandb: True
wandb_tags:
  - time_window-10
  - relative_l2_loss
  - AViT-Defaultt
  - PB-Subcooled
defaults:
  - _self_
  - data_cfg: poolboiling_subcooled
  - model_cfg: avit_small
  - optim_cfg: adamw
  - scheduler_cfg: cosine_warmup
