log_dir: /pub/sheikhh1/bubbleformer_logs
seed: 42

nodes:
devices:

max_epochs:
batch_size:

checkpoint_path:

use_wandb: True
wandb_tags:
  - time_window-5
  - relative_l2_loss
  - AViT-Default
  - SingleBubble
  - Lion optimizer
defaults:
  - _self_
  - data_cfg: singlebubble
  - model_cfg: avit_small
  - optim_cfg: lion
  - scheduler_cfg: cosine_warmup
