dataset: bubbleml_subcooled
normalize: none
downsample_factor: 1
input_fields: ["dfun", "temperature", "velx", "vely"]
output_fields: ["temperature", "velx", "vely"]
time_window: 5
start_time: 300
train_paths:
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-90.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-92.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-95.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-97.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-98.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-100.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-102.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-106.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-108.hdf5
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-110.hdf5
val_paths:
  - /share/crsp/lab/amowli/share/BubbleML2/PoolBoiling-SubCooled-FC72-2D-0.1/Twall-103.hdf5