dataset: flowboiling_velscale
input_fields: ["dfun", "temperature", "velx", "vely"]
output_fields: ["dfun", "temperature", "velx", "vely"]
normalize: none
downsample_factor: 1
time_window: 5
start_time: 100
return_fluid_params: False
train_paths:
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-1.5.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-1.6.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-1.7.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-1.8.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-1.9.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.0.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.1.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.3.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.4.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.5.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.6.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.7.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.8.hdf5
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.9.hdf5
val_paths:
  - /share/crsp/lab/ai4ts/share/simul_ts_0.1/FlowBoiling-VelScale-FC72-2D-0.1/inletVelScale-2.2.hdf5
