dataset: poolboiling_saturated
input_fields: ["dfun", "temperature", "velx", "vely"]
output_fields: ["dfun", "temperature", "velx", "vely"]
normalize: none
downsample_factor: 1
time_window: 5
start_time: 100
return_fluid_params: True
train_paths:
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_76.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_78.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_80.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_82.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_84.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_86.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_88.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_90.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_92.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_94.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_96.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_98.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_100.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_102.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_104.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_106.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_5.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_7.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_9.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_11.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_13.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_15.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_17.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_19.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_21.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_23.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_25.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_27.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_29.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_31.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_33.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_35.hdf5
val_paths:
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-FC72-2D/Twall_91.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Saturated-R515B-2D/Twall_18.hdf5