dataset: poolboiling_subcooled
input_fields: ["dfun", "temperature", "velx", "vely"]
output_fields: ["dfun", "temperature", "velx", "vely"]
normalize: none
downsample_factor: 1
time_window: 5
start_time: 100
return_fluid_params: True
train_paths:
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_86.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_88.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_90.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_92.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_94.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_96.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_98.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_100.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_102.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_104.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_106.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_108.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_110.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_112.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_114.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_116.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_15.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_17.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_19.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_21.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_23.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_25.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_27.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_29.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_31.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_33.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_35.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_37.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_39.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_41.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_43.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_45.hdf5
val_paths:
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-FC72-2D/Twall_97.hdf5
  - /share/crsp/lab/amowli/share/Bubbleformer/PoolBoiling-Subcooled-R515B-2D/Twall_30.hdf5
